
version: 2

models:
  
  - name: stg_users
    description: "Customers"
    columns:
      - name: user_id
        description: "Customer PK"
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null