
version: 2

models:
  
  - name: avg_orders_per_hour
    description: tbd

  - name: avg_unique_sessions_per_hour
    description: tbd
  
  - name: how_many_users_made_n_purchases
    description: tbd
    
    
