
version: 2

models:
  
  - name: stg_users
    description: "Customers"
    columns:
      - name: user_id
        description: "Customer PK"
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: email
        tests:
          - not_null
      - name: phone_number
        tests:
          - not_null
  
  - name: stg_promos
    description: tbd
    columns:
      - name: promo_id
        description: "pk"
        tests:
          - unique
          - not_null
      - name: discount
        description: "tbd"
        tests:
          - not_null
      - name: status
        description: "tbd"
        tests:
          - not_null
          - accepted_values:
              values: ['inactive','active']

  - name: stg_products
    description: tbd
    columns:
      - name: product_id
        description: PK
        tests:
          - unique
          - not_null
      - name: name
        description: tbd
        tests:
          - unique
          - not_null
      - name: price
        description: tbd
        tests:
          - not_null
          - positive_values
      - name: inventory
        description: tbd
        tests:
          - not_null
          - positive_values

  - name: stg_orders
    description: tbd
    columns:
      - name: order_id
        description: tbd
        tests:
          - unique
          - not_null
      - name: user_id
        description: tbd
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id  
      - name: address_id
        description: tbd
        tests:
          - not_null
          - relationships:
              to: ref('stg_addresses')
              field: address_id  
      - name: order_cost
        description: tbd
        tests:
          - not_null
          - positive_values
      - name: shipping_cost
        description: tbd
        tests:
          - not_null
          - positive_values 
      - name: order_total
        description: tbd
        tests:
          - not_null
          - positive_values 
      - name: shipping_service
        description: tbd
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['fedex','dhl','ups','usps']
              quote_values: true
              row_condition: "shipping_service is not null"

  - name: stg_order_items
    description: tbd
    columns:
      - name: order_id
        description: tbd
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id        
      - name: product_id
        description: tbd
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id  
      - name: quantity
        description: tbd
        tests:
          - not_null
          - positive_values

  - name: stg_events
    description: tbd
    columns:
      - name: event_id
        description: tbd
        tests:
          - not_null
          - unique
      - name: session_id
        description: tbd
        tests:
          - not_null
      - name: user_id
        description: tbd
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id
      - name: page_url
        description: tbd
        tests: 
          - not_null
      - name: event_type
        description: tbd
        tests:
          - not_null
          - accepted_values:
              values: ['checkout','package_shipped','add_to_cart','page_view']    
      - name: order_id
        description: tbd
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id     
      - name: product_id
        description: tbd
        tests:
          - relationships:
              to: ref('stg_products')
              field: product_id        
  - name: stg_addresses
    description: tbd
    columns:
      - name: address_id
        description: tbd
        tests:
          - not_null
          - unique
      - name: address
        description: tbd
        tests:
          - not_null
      - name: zipcode
        description: tbd
        tests: 
          - not_null
      - name: state
        description: tbd
        tests:
          - not_null
      - name: country
        description: tbd
        tests: 
          - not_null

  - name: avg_orders_per_hour
    description: tbd
  
  - name: how_many_users_made_n_purchases
    description: tbd
    
    
